# print("My name is \"Afreen\"")
# print("Dont do \"this\"")
# # print("\"this is important\"")
# print("this sign \\ is a backslash")
# print("This is one line\nand this is another")
# print("\tthis is the third line")
# print('There isn\'t a number')
# print('A\tB\t\tC\nD\tE\t\tF\nG\tH\t\tI\n')
# print("/")
# print("\\")

print("Backslash (\\)")
print("Forward Slash (/)")