# Generated by Django 4.2.2 on 2023-06-18 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["complete"]},
        ),
    ]
